services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "envato/build-failed-notify-slack"]
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester:v3.0.1
    volumes:
      - ".:/plugin:ro"
