#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/pipeline.bash
source "$DIR/../lib/pipeline.bash"

echo "~~~ Contents of notify pipeline"

pipeline

echo "+++ Uploading notify pipeline"

pipeline | buildkite-agent pipeline upload