---
name: tests
on: [push]
jobs:
  plugin-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tests
        run: docker run --rm -v "$PWD:/plugin:ro" buildkite/plugin-tester:v3.0.1
  plugin-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: docker run --rm -v "$PWD:/plugin:ro" buildkite/plugin-linter:latest --id envato/build-failed-notify-slack
  plugin-shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: "yes"
